# Generated by Django 4.1.7 on 2023-08-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0002_piano_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
